channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch-cuda=11.7
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch=2.0.1
  - ipykernel
  - matplotlib
  - mypy
  - pylint
  - isort